### PR TITLE
Upload screenshots

### PR DESCRIPTION
**Pull request by AakarshitAgarwal**
## Issue that this pull request solves

Closes: # (issue number)

## Proposed changes

Brief description of what is fixed or changed

## Types of changes

_Put an `x` in the boxes replacing ' ' that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by priyansh19** [comment]
@AakarshitAgarwal you haven't added info while creating a PR 
and also rename your Screenshot with the mentioned format

**Comment by lakshay4040** [comment]
@AakarshitAgarwal upload the screenshot as it is mentioned in the details of the issue.

**Comment by AakarshitAgarwal** [comment]
@priyansh19 sir I had added the ss , please check the PR.

**Comment by priyansh19** [comment]
Also, add your Screenshot when you make a PR 
Make it a habit it helps maintainers to check for your functionality directly

Add ss here in comment section and then you are good to go

**Comment by priyansh19** [comment]
This time we are merging :+1: your pr

**Pull request merged**
